### ISSUE TITLE
Need help: missing port in address

### ISSUE THREAD

**Issue by Dmdv** [xpunch/go-micro-example#2] opened 2021-11-24 08:47 UTC
Hi, I need help, there's something missing on my side.

I'm trying to run examples from v4

I run service without errors:

```
dima@Dimas-MBP ~/g/g/v/helloworld (main)> go run server/main.go --server grpc --server_name helloworld.srv                                                                                          11:40:16
2021-11-24 11:43:04  file=v4@v4.4.0/service.go:206 level=info Starting [service] helloworld.srv
2021-11-24 11:43:04  file=v4@v4.0.0-20211111140334-799b8d6a6559/grpc.go:894 level=info Server [grpc] Listening on [::]:49954
2021-11-24 11:43:04  file=v4@v4.0.0-20211111140334-799b8d6a6559/grpc.go:725 level=info Registry [mdns] Registering node: helloworld.srv-2a7e786e-ca6c-4ac8-983a-ca3495df5075
```

But client always fails. And the same is for other examples in go-micro repo

```
dima@Dimas-MBP ~/g/g/v/helloworld (main)> go run client/main.go --client grpc                                                                                                                       11:43:41
2021-11-24 11:44:03  file=client/main.go:22 level=fatal {"id":"go.micro.client","code":503,"detail":"connection error: desc = \"transport: Error while dialing dial tcp: address [[fd55:XXX:a505]]:49954: missing port in address\"","status":"Service Unavailable"}
exit status 1
```

**Comment by Dmdv** [comment] 2021-11-24 08:56
It seems mdns is not resolving...

**Comment by xpunch** [comment] 2021-11-24 08:58
Could be ipv6 issue, I'll take a look.

**Comment by Dmdv** [comment] 2021-11-24 09:09
> Could be ipv6 issue, I'll take a look.

Thank you. Also, looking at possible mdsn issues in Mac.
I've been thinking that using etcd would be best option because the service will be working in kuber anyway. But at least I need a way to debug the service locally

**Comment by Dmdv** [comment] 2021-11-24 09:12
Perhaps this could help?
https://github.com/hashicorp/mdns/blob/f504e0b3c01cf50e077ab6805546fa95ed9f2933/client.go#L111

**Comment by xpunch** [comment] 2021-11-24 09:17
Your ipv6 address [[fd55:XXX:a505]]:49954 cannot be parsed by net.SplitHostPort

**Comment by Dmdv** [comment] 2021-11-24 09:21
> Your ipv6 address [[fd55:XXX:a505]]:49954 cannot be parsed by net.SplitHostPort

fd55:e0da:f8c9:3:cd7:c048:5b48:a505

**Comment by xpunch** [comment] 2021-11-24 09:22
Your ipv6 address was wrapped by [[]], should be [].

**Comment by xpunch** [comment] 2021-11-24 09:23
try run your server with --server_advertise [fd55:e0da:f8c9:3:cd7:c048:5b48:a505]:port

**Comment by Dmdv** [comment] 2021-11-24 09:24
> Your ipv6 address was wrapped by [[]], should be [].
This is a part of log entry, so brackets could be added by a loger
```
dial tcp: address [[fd55:e0da:f8c9:3:cd7:c048:5b48:a505]]:53813: missing port in address","status":"Internal Server Error"
```

**Comment by xpunch** [comment] 2021-11-24 09:27
No, the logger will not add that.

**Comment by xpunch** [comment] 2021-11-24 09:27
Check your ip config.

**Comment by Dmdv** [comment] 2021-11-24 09:27
```
dima@Dimas-MBP ~/g/g/v/helloworld (main) [1]> go run server/main.go --server grpc --server_advertise [fd55:e0da:f8c9:3:cd7:c048:5b48:a505]:49954 --server_name helloworld.srv                       12:26:01
2021-11-24 12:26:38  file=v4@v4.4.0/service.go:206 level=info Starting [service] helloworld.srv
2021-11-24 12:26:38  file=v4@v4.0.0-20211111140334-799b8d6a6559/grpc.go:894 level=info Server [grpc] Listening on [::]:52735
2021-11-24 12:26:38  file=v4@v4.0.0-20211111140334-799b8d6a6559/grpc.go:725 level=info Registry [mdns] Registering node: helloworld.srv-d0da1fb0-9f37-4b85-bd8e-09b9742dfa37
```

Client response:

```
dima@Dimas-MBP ~/g/g/v/helloworld (main) [1]> go run client/main.go --client grpc                                                                                                                   12:25:45
2021-11-24 12:26:52  file=client/main.go:22 level=fatal {"id":"go.micro.client","code":503,"detail":"connection error: desc = \"transport: Error while dialing dial tcp: address [[fd55:e0da:f8c9:3:cd7:c048:5b48:a505]]:49954: missing port in address\"","status":"Service Unavailable"}
exit status 1
```

**Comment by Dmdv** [comment] 2021-11-24 09:31
> Check your ip config.

yes, that address without brackets

**Comment by xpunch** [comment] 2021-11-24 09:33
Your ipv6 address was wrapped by extra [] by unknown code, I cannot reproduce your issue, you can debug the grpc client to found out who changed the ipv6 address.

**Comment by Dmdv** [comment] 2021-11-24 09:53
Actually, I just took the example, didn't change anything.
Ok

**Comment by xpunch** [comment] 2021-11-24 10:01
I know, but I cannot reproduce your issue and I could not figure out who updated your ipv6 address.

**Comment by Dmdv** [comment] 2021-11-24 12:54
I will use another service discovery, considering that it will be working in K8S anyway.
Is there any documentation regarding how to run service and client with different service providers, such as etcd and kubernetes?

I understood that we can use plugins directly when starting the service or with command line arguments provided that we have added plugins as import in the code.

Also, if I debug service/client locally, what is the best practice, is it to run with a service provider running in localhost?

**Comment by Dmdv** [comment] 2021-11-24 21:33
I tested it in the kubernetes

Server:

```
Starting transaction-persistence
2021/11/24 20:17:17 debug logging disabled
2021/11/24 20:17:17 debug logging disabled
2021-11-24 20:17:17  file=v4@v4.4.0/service.go:206 level=info Starting [service] transaction-persistence
2021-11-24 20:17:17  file=server/rpc_server.go:820 level=info Transport [http] Listening on 127.0.0.1:9845
2021-11-24 20:17:17  file=server/rpc_server.go:840 level=info Broker [http] Connected to 127.0.0.1:37177
2021-11-24 20:17:17  file=server/rpc_server.go:654 level=info Registry [kubernetes] Registering node: transaction-persistence-4148a175-ca8a-41d2-9f9f-7acd5971726f
```

The client:

```
2021-11-24 21:28:30  file=tx-persistence-client/main.go:33 level=fatal {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 127.0.0.1:9845: connect: connection refused","status":"Internal Server Error"}

Process finished with exit code 0

```

**Comment by Dmdv** [comment] 2021-11-24 21:34
I used skaffold to deploy it in kubernetes

**Comment by Dmdv** [comment] 2021-11-24 22:01
Locally it fixed.
I did nothing, just added grpc plugins and added to scaffold env variables:
MICRO_CLIENT:grpc
MICRO_SERVER:grpc

And run services and client with micro run.
But server still uses http:

```
2021-11-25 00:57:34  file=v4@v4.4.0/service.go:206 level=info Starting [service] transaction-persistence
2021-11-25 00:57:34  file=server/rpc_server.go:820 level=info Transport [http] Listening on 127.0.0.1:9845
2021-11-25 00:57:34  file=server/rpc_server.go:840 level=info Broker [http] Connected to 127.0.0.1:60980
2021-11-25 00:57:34  file=server/rpc_server.go:654 level=info Registry [mdns] Registering node: transaction-persistence-29358234-6a1c-45eb-9663-01af34f9b263
```

**Comment by xpunch** [comment] 2021-11-25 01:58
So you set your server address to 127.0.0.1:9845?

**Comment by Dmdv** [comment] 2021-11-25 07:40
I didn't change the address. I realised that I can update env variables like MICRO_***

Do you mind if I create service and client with default config?
Because after I switch to grpc transport it stopped working, the client fails with error:

```
2021-11-25 03:03:28  file=tx-persistence-client/main.go:33 level=fatal {"id":"go.micro.client","code":500,"detail":"service transaction-persistence: not found","status":"Internal Server Error"}
exit status 1
```

**Comment by Dmdv** [comment] 2021-11-25 07:41
I'll ping once I've posted sample project
Also this didn't work:
https://github.com/xpunch/go-micro-example/tree/main/v3/helloworld

Server runs fine but client fails

```
# command-line-arguments
./main.go:98:18: stream.CloseSend undefined (type "github.com/xpunch/go-micro-example/v4/stream/proto".RouteGuide_RecordRouteService has no field or method CloseSend)
./main.go:146:18: stream.CloseSend undefined (type "github.com/xpunch/go-micro-example/v4/stream/proto".RouteGuide_RouteChatService has no field or method CloseSend)
```

**Comment by Dmdv** [comment] 2021-11-25 13:24
@xpunch 
I've created server and client and run it with 
```skaffold run ```
or
```micro run ```

The output is the same:


Server:
```
2021-11-25 13:35:07  file=micro-server/main.go:23 level=info Starting micro-server
2021-11-25 13:35:07  file=v4@v4.4.0/service.go:206 level=info Starting [service] go.micro.server
2021-11-25 13:35:07  file=v4@v4.0.0-20211124174154-b25d744f5c51/grpc.go:894 level=info Server [grpc] Listening on [::]:36003
2021-11-25 13:35:07  file=v4@v4.0.0-20211124174154-b25d744f5c51/grpc.go:725 level=info Registry [kubernetes] Registering node: go.micro.server-7ad54c44-a8d9-4b39-b59c-3bf33154ec06
```

Client:

```
2021-11-25 16:32:40  file=micro-client/main.go:33 level=fatal {"id":"go.micro.client","code":500,"detail":"service micro-server: not found","status":"Internal Server Error"}
exit status 1
2021-11-25 16:32:40  file=runtime/service.go:217 level=error Service /Users/dima/go/micro-client terminated with error exit status 1
```

Client can never connect to the server

**Update:**
I found the reason: the server name is `go.micro.server` for whatever reason 
although I specified it explicitly with **ServerName**

**Comment by xpunch** [comment] 2021-11-26 02:04
It's a known issue: https://github.com/asim/go-micro/issues/2140.

**Comment by xpunch** [comment] 2021-11-30 01:44
I'll close this issue too.

**Closed as completed by xpunch** 2021-11-30 01:44 UTC
